[project]
name = "curso-sql"
version = "0.1.0"
description = "Curso de SQL"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ipykernel>=6.30.1",
    "kaggle>=1.7.4.5",
    "pandas>=2.3.2",
    "sqlalchemy>=2.0.43",
]
